# Model Building

## Implementing Formula on our Dataset

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('FinalDataset.csv')
df.head()

Unnamed: 0  amount_of_loan  interest_rate  time_to_repay  simple_interest  \
0           0         3331276             13              3                1   
1           1         6690555              9              2                1   
2           2         5039662             12              4                1   
3           3         6230007             13              3                0   
4           4         1615383             13              2                1   

   cibil_score  past_debt_to_repay  profit_percentage_last_year  \
0          760             1549433                            1   
1          713             1577994                           21   
2          761             4555691                           34   
3          637             2529141                           11   
4          791             1700947                           32   

   competition_scale  sustainability  startup  management_effectivity  \
0                  4               1        0                       0   
1                  4               1        0                       1   
2                  7               1        1                       0   
3                  3               0        0                       0   
4                  8               0        0                       0   

   Total_Revenue  
0       10758375  
1        9835290  
2       11539840  
3        7759170  
4        6482400

In [3]:
df.drop(columns = ['Unnamed: 0'], inplace = True)
df.head()

amount_of_loan  interest_rate  time_to_repay  simple_interest  cibil_score  \
0         3331276             13              3                1          760   
1         6690555              9              2                1          713   
2         5039662             12              4                1          761   
3         6230007             13              3                0          637   
4         1615383             13              2                1          791   

   past_debt_to_repay  profit_percentage_last_year  competition_scale  \
0             1549433                            1                  4   
1             1577994                           21                  4   
2             4555691                           34                  7   
3             2529141                           11                  3   
4             1700947                           32                  8   

   sustainability  startup  management_effectivity  Total_Revenue  
0               1        0                       0       10758375  
1               1        0                       1        9835290  
2               1        1                       0       11539840  
3               0        0                       0        7759170  
4               0        0                       0        6482400

## Calculating Risk Factor

In [4]:
from LoanCostFunction import loan_cost_prediction

In [5]:
risk = []
cnt = 0
for i in range(0, 3000):
    risk.append(loan_cost_prediction(df['Total_Revenue'][i], df['profit_percentage_last_year'][i], df['simple_interest'][i], df['interest_rate'][i], df['amount_of_loan'][i], df['time_to_repay'][i], df['past_debt_to_repay'][i], df['sustainability'][i], df['competition_scale'][i], df['management_effectivity'][i], df['startup'][i], df['cibil_score'][i]))

In [6]:
df['Risk_Factor'] = risk
df.head()

amount_of_loan  interest_rate  time_to_repay  simple_interest  cibil_score  \
0         3331276             13              3                1          760   
1         6690555              9              2                1          713   
2         5039662             12              4                1          761   
3         6230007             13              3                0          637   
4         1615383             13              2                1          791   

   past_debt_to_repay  profit_percentage_last_year  competition_scale  \
0             1549433                            1                  4   
1             1577994                           21                  4   
2             4555691                           34                  7   
3             2529141                           11                  3   
4             1700947                           32                  8   

   sustainability  startup  management_effectivity  Total_Revenue  Risk_Factor  
0               1        0                       0       10758375           -2  
1               1        0                       1        9835290           -2  
2               1        1                       0       11539840           -2  
3               0        0                       0        7759170           -2  
4               0        0                       0        6482400           -2

## Model Training

In [7]:
target = df.iloc[:, -1]

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(df.drop('Risk_Factor',axis='columns'), target, test_size=0.3)

In [9]:
from sklearn import tree
model = tree.DecisionTreeClassifier()
model.fit(X_train, Y_train)

DecisionTreeClassifier()

## Predicting Testcases

### High Profit

In [10]:
model.predict([[2200000, 10, 8, 0, 850, 2600000, 40, 10, 0, 0, 0, 15000000]])

C:\Users\daksh\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([2], dtype=int64)

### High Risk

In [11]:
model.predict([[8650000, 6, 8, 1, 400, 3500000, 1, 3, 0, 0, 1, 9260000]])

C:\Users\daksh\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([-2], dtype=int64)

### Less Profit

In [12]:
model.predict([[8400000, 13, 8, 0, 500, 1230000, 25, 6, 0, 0, 1, 13468000]])

C:\Users\daksh\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([2], dtype=int64)

### Less Risk

In [13]:
model.predict([[7800000, 12, 9, 0, 800, 1100000, 25, 10, 1, 0, 0, 9300000]])

C:\Users\daksh\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([2], dtype=int64)

### Score of the model

In [14]:
model.score(X_test, Y_test)

0.8711111111111111

### Making a function for model

In [15]:
def main(a,b,c,d,e,f,g,h,i,j,k,l):
    return model.predict([[a,b,c,d,e,f,g,h,i,j,k,l]])

## User Interface Widget

In [16]:
import ipywidgets as widgets
from IPython.display import display

In [17]:
#revenue input
revenue = widgets.IntText(description='Revenue:',disabled=False)
display(revenue)

#Profit% last year input
profit_percentage_last_year= widgets.IntText(description='Profit% last year:',disabled=False,style= {'description_width': 'initial'})
display(profit_percentage_last_year)

#Interest rate input
interest_rate= widgets.IntSlider(description="Interest rate in %",disabled=False,style= {'description_width': 'initial'})
display(interest_rate)

#Amount of Loan input
amount_of_loan = widgets.IntText(description="Amount of Loan",disabled=False,style= {'description_width': 'initial'})
display(amount_of_loan)

#Time to repay input
time_to_repay=widgets.IntText(description="Time to repay",disabled=False,style= {'description_width': 'initial'})
display(time_to_repay)

#simple interest input
simple_interest=widgets.ToggleButtons(description="Simple interest or not",options=[1,0],disabled=False,style= {'description_width': 'initial'})
display(simple_interest)

#Past debt to repay input
past_debt_to_repay=widgets.IntText(description="Past debt to repay",disabled=False,style= {'description_width': 'initial'})
display(past_debt_to_repay)

#Sustainability input
sustainability=widgets.IntText(description="Sustainability",disabled=False,style= {'description_width': 'initial'})
display(sustainability)

#competition scale input
competition_scale=widgets.IntSlider(min = 0, max = 10, step = 1, description="Competition Scale",disabled=False,style= {'description_width': 'initial'})
display(competition_scale)

#managment effectivitely input
management_effectivity=widgets.ToggleButtons(description="Managment Effectivitely",options=[1,0],disabled=False,style= {'description_width': 'initial'})
display(management_effectivity)

#startup input
startup = widgets.ToggleButtons(description="Whether a startup or not",options=[1,0],disabled=False,style= {'description_width': 'initial'})
display(startup)

#cibil score input
cibil_score=widgets.IntText(min = 300, max = 900 , description="Cibil Score",disabled=False,style= {'description_width': 'initial'})
display(cibil_score)

IntText(value=0, description='Revenue:')

IntText(value=0, description='Profit% last year:', style=DescriptionStyle(description_width='initial'))

IntSlider(value=0, description='Interest rate in %', style=SliderStyle(description_width='initial'))

IntText(value=0, description='Amount of Loan', style=DescriptionStyle(description_width='initial'))

IntText(value=0, description='Time to repay', style=DescriptionStyle(description_width='initial'))

ToggleButtons(description='Simple interest or not', options=(1, 0), style=ToggleButtonsStyle(description_width…

IntText(value=0, description='Past debt to repay', style=DescriptionStyle(description_width='initial'))

IntText(value=0, description='Sustainability', style=DescriptionStyle(description_width='initial'))

IntSlider(value=0, description='Competition Scale', max=10, style=SliderStyle(description_width='initial'))

ToggleButtons(description='Managment Effectivitely', options=(1, 0), style=ToggleButtonsStyle(description_widt…

ToggleButtons(description='Whether a startup or not', options=(1, 0), style=ToggleButtonsStyle(description_wid…

IntText(value=0, description='Cibil Score', style=DescriptionStyle(description_width='initial'))

In [18]:
# print("Revenue", revenue.value)
# print("profit percentage last year" ,profit_percentage_last_year.value)
# print("interest rate (in %)" ,interest_rate.value)
# print("amount of loan (in INR)" ,amount_of_loan.value)
# print("time to repay (in years)",time_to_repay.value)
# print("simple interest (1) / Compound Interest (0)",simple_interest.value)
# print("past debt to repay (in INR)",past_debt_to_repay.value)
# print("sustainability (1/0)", sustainability.value)
# print("competition scale (out of 10)" ,competition_scale.value)
# print("management effectivity (1/0)" ,management_effectivity.value)
# print("startup or not (1/0)" ,startup.value)
# print("cibil score (300 - 900)", cibil_score.value)

button = widgets.Button(description="Check Risk Factor")
output = widgets.Output()

display(button, output)

def on_button_clicked(b):
    with output:
        
        decision = main(revenue.value, profit_percentage_last_year.value, interest_rate.value \
        , amount_of_loan.value, time_to_repay.value, simple_interest.value, past_debt_to_repay.value, \
        sustainability.value, competition_scale.value, management_effectivity.value, startup.value, cibil_score.value)
        if decision <= -1.5:
            print("High Loss Risk, Please avoid taking new loans. High possibility to fall in debt trap !")
        elif -1.5 < decision < 0:
            print("Loss Risk, please think twice before taking a new loan")
        elif 0 <= decision < 1.5:
            print("Small Profit, Avoid taking unnecessary large loans.")
        else:
            print("Good Vibe! You can surely take loan")


button.on_click(on_button_clicked)



Revenue 0
profit percentage last year 0
interest rate (in %) 0
amount of loan (in INR) 0
time to repay (in years) 0
simple interest (1) / Compound Interest (0) 1
past debt to repay (in INR) 0
sustainability (1/0) 0
competition scale (out of 10) 0
management effectivity (1/0) 1
startup or not (1/0) 1
cibil score (300 - 900) 0


C:\Users\daksh\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


Good Vibe! You can surely take loan


In [20]:
!pip freeze > requirements.txt